const STORY_TURNS_PER_HOUR = 1200
const STORY_PHASE_HOURS = 3
const STORY_TURNS_PER_PHASE = STORY_TURNS_PER_HOUR * STORY_PHASE_HOURS
const STORY_DAY_TURNS = STORY_TURNS_PER_HOUR * 24
const DIALOGUE_REPEAT_WINDOW_TURNS = STORY_TURNS_PER_HOUR

module.exports = {
	DIALOGUE_REPEAT_WINDOW_TURNS,
	STORY_DAY_TURNS,
	STORY_PHASE_HOURS,
	STORY_TURNS_PER_HOUR,
	STORY_TURNS_PER_PHASE
}
